---
galaxy_info:
  author: farzadafi
  description: Install Docker packages from deb files and ensure docker is installed for ubuntu 22
  license: ProgrammingByFarzadAfi
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - 22.04
dependencies: []
