---
galaxy_info:
  author: farzadafi
  description: Copy Docker .deb files if missing for ubuntu 22 jammy
  license: ProgrammingByFarzadAfi :)
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - 22.04
dependencies: []
